name: Build & Deploy .NET Framework App

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'DummyFrameworkApp/**'
      - '.github/workflows/dotnet-framework.yml'
      - '.github/action/**'

jobs:
  build-and-deploy:
    runs-on: self-hosted # Runner laptop/server build kamu

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute Composite Build & Deploy Action
        uses: ./.github/action/dotnet-framework-build-deploy
        with:
          solution-path: 'DummyFrameworkApp.sln'
          build-configuration: 'Release'
          publish-dir: '_publish'
          target-host: ${{ secrets.DEPLOY_TARGET_HOST }}
          target-user: ${{ secrets.DEPLOY_TARGET_USER }}
          target-password: ${{ secrets.DEPLOY_TARGET_PASSWORD }}
          remote-deploy-path: 'C:\inetpub\wwwroot\DummyFrameworkApp'